Add controllers
pavlovartem97/java-shareit pull request #1
Opened 2023-05-26 09:07 UTC by pavlovartem97

2023-05-26 19:07 UTC, kalitva requested changes

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @RequestHeader("X-Sharer-User-Id") long userId) {
Давай вынесем `X-Sharer-User-Id` в константу

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.addItem(dto, userId);
Предлагаю переместить все мапперы в контроллеры чтобы сервисы возвращали и принимали модели а не дто

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemDao.java
> +    Collection<Item> findByStr(String str);
Избегай использования абстрактных названий типа `string, value, data` и также избегай сокращений

`str --> query или text или searchText или searchQuery`

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemDaoInMemoryImpl.java
> +        return Optional.ofNullable(items.getOrDefault(itemId, null));
`items.getOrDefault(itemId, null) --> items.get(itemId)`

И так вернется null

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private final UserService userService;
Желательно использовать `userRepository` чтобы избежать циклических зависимостей

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User addUser(@RequestBody @Valid UserCreateDto userDto) {
Возвращать тоже желательно дто

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserDaoInMemoryImpl.java
> +public class UserDaoInMemoryImpl implements UserDao {
`UserDaoInMemoryImpl --> InMemoryUserDao`

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserDao.java
> +    Set<String> findAllEmail();
Лучше сделать что-то типа

`boolean existsByEmail(long userId)`

Нам то сами имэйлы не нужны, нужно только проверить на уникальность

2023-05-26 19:07 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/dto/UserUpdateDto.java
> +    /** Имя пользователя */
Думаю, в дтошках эти комменты не нужны

2023-05-28 15:53 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.addItem(dto, userId);
Мне кажется логисным всю логику по обработке dto осуществлять в сервисах, включая маппинг входных и выходных dto.

2023-05-28 16:04 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/user/dto/UserUpdateDto.java
> +    /** Имя пользователя */
В больших приложениях может быть путаница в dto без комментариев + часто служат документацией для фронтов, которые потенциально будут отправлять и принимать dto.

2023-05-28 18:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        return itemService.addItem(dto, userId);
Окей

2023-05-28 18:29 UTC, kalitva approved these changes

2023-05-28 18:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/InMemoryItemDao.java
> +    public Collection<Item> findByStr(String searchText) {
`findByStr --> findBySearchText`

2023-05-28 18:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/exception/ItemErrorHandler.java
> +public class ItemErrorHandler {
`ItemErrorHandler --> ErrorHandler` В `ControllerAdvice` следует отлавливать исключения, вылетевшие из любых контроллеров. Если ты хочешь отлавливать исключения только из `ItemService` следует определить `@ExceptionHandler` в  `ItemController`

2023-05-28 18:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/exception/ItemErrorHandler.java
> +    @ExceptionHandler({ItemNotFoundException.class, OwnerIsNotValidException.class})
Думаю, нет смысла определять для каждого кейса свое исключение. Для всех исключений типа NOT_FOUND хватит одного `NotFoundException`. У нас далее в этом проекте будут еще кейсы, где уместно следует вернуть 404

Плюс мне кажется для `OwnerIsNotValidException` лучше вернуть статус BAD_REQUEST

2023-05-28 18:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @PatchMapping("{userId}")
`@PatchMapping("/{userId}")` Спринг автоматически нормализует пути, но будет хорошей практикой не пропускать ведущий слэш

2023-05-28 18:29 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/exception/UserErrorHandler.java
> +    @ExceptionHandler(UserNotFoundException.class)
Тоже, либо перенеси в юзер-контроллер, либо лови в общем контроллере `@RestControllerAdvice`. Плюс еще есть такой вариант - ставишь `@ResponseStatus(...` над самим исключением и спринг автоматически его перехватит и вернет нужный статус

2023-07-10 16:00 UTC, merged