Add bookings
pavlovartem97/java-shareit pull request #2
Opened 2023-07-17 22:13 UTC by pavlovartem97

2023-07-18 20:16 UTC, kalitva requested changes

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(value = "state", required = false, defaultValue = "ALL") String state,
Насколько я помню, наличие `defaultValue` снимает необходимсоть указывать `required = false`, проверь в javadocs аннотации

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingCustomRepository.java
> +    private EntityManager entityManager;
Обычно для выборки по фильтрам используют спринговый `Specification` для работы с criteria api, почитай эту статью

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

Это необязательно, такая реализация тоже хорошая

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Autowired
1. Использование field injection считается не очень хорошей практикой
2. В данном случае в `@Autowired` нет необходимости, так как у нас есть конструктор для всех этих полей

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        return Map.of("error", e.getMessage());
Давай залогируем исключение

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/CommentService.java
> +public class CommentService {
Не понял, зачем нужен пустой сервис?

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        });
Можно сделать этот хэшмап с помощью стрим апи, погугли как использовать `Collectors#grouppingBy`

2023-07-18 20:16 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/dto/CommentDtoIn.java
> +    ;
Удали лишний семиколон

2023-07-18 20:16 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS sh_comment CASCADE;
Не думаю что это хорошая идея - дропать данные при каждом запуске приложения. Ты же подключаешься к h2 когда тестируешь? Достаточно просто перезапустить приложение чтобы очистить h2

Кстати, можешь попробовать использовать spring-boot-devtools чтобы было удобнее перезапускать после изменений

2023-07-18 20:16 UTC, kalitva commented on src/main/resources/schema.sql
> +  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
Давай лучше использовать 4 отступа, как во всех остальных файлах

2023-07-18 20:16 UTC, kalitva commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  package ru.practicum.shareit;
Думаю, лучше вообще удалить этот файл

2023-07-18 20:36 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +            @RequestParam(value = "state", required = false, defaultValue = "ALL") String state,
![image](https://github.com/pavlovartem97/java-shareit/assets/111424160/5f377158-d7ec-4a3d-b080-22828933c28d)
И правду не нужен

2023-07-18 20:40 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/booking/BookingCustomRepository.java
> +    private EntityManager entityManager;
Спасибо за статью, на работе для работы с фильтрами с множеством предикатов чаще используется предложенная мной схема

2023-07-18 20:41 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    @Autowired
Изменял из-за проблем со сборкой на гите. Проблема оказалась в другом

2023-07-18 20:43 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/item/CommentService.java
> +public class CommentService {
Случайно

2023-07-19 16:06 UTC, kalitva approved these changes

2023-07-19 16:06 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +                                                     @Param("now") LocalDateTime now);
Текущий таймстамп можно получить на стороне БД

2023-07-19 16:06 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                    @PathVariable("itemId") long itemId) {
`@PathVariable("itemId") --> @PathVariable`

2023-08-21 04:30 UTC, merged