Add item requests
pavlovartem97/java-shareit pull request #3
Opened 2023-08-21 11:22 UTC by pavlovartem97

2023-08-22 15:09 UTC, kalitva requested changes

2023-08-22 15:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.error(e.getMessage());
`log.error(e.getMessage(), e);`
Давай залогируем стэктрэйс

2023-08-22 15:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +import static ru.practicum.shareit.util.Utils.checkFromAndSize;
Пожалуйста, давай обойдемся без статических импортов (допустимо только в тестах)

2023-08-22 15:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/RequestRepository.java
> +            "OFFSET :offset ", nativeQuery = true)
Почему `nativeQuery`? Лучше используй hql

2023-08-22 15:09 UTC, kalitva commented on src/main/java/ru/practicum/shareit/util/Utils.java
> +        if (from < 0 || size < 1) {
Используй `@Positive` и `@PositiveOrNull` для валидации этих значений прямо в параметрах метода контроллера. Для этого к контроллеру надо добавить спринговый `@Validated`

2023-08-22 15:09 UTC, kalitva commented on src/test/java/ru/practicum/shareit/BaseTest.java
> +public abstract class BaseTest {
Не думаю, что это хорошая идея - создавать иерархию в тестовых классах, которая не соответствует тестируемым.  Для данных создай утилитный класс

2023-08-22 15:09 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingCustomDaoTest.java
> +    BookingCustomRepository bookingCustomRepository;
private

2023-08-22 20:16 UTC, pavlovartem97 commented on src/test/java/ru/practicum/shareit/BaseTest.java
> +public abstract class BaseTest {
Тут зависит от подхода, у нас на работе во всех микросервсах принято использовать некий базовый класс, содержащий тестовую конфигурацию, которая обычно намного сложнее (пример на фото). Такой подход позволяет не перетаскивать новые аннотации на все тесты при их большом количестве
![image](https://github.com/pavlovartem97/java-shareit/assets/111424160/198e024a-f855-4fec-989c-035d9ce03e99)

2023-08-22 20:22 UTC, pavlovartem97 commented on src/main/java/ru/practicum/shareit/request/RequestRepository.java
> +            "OFFSET :offset ", nativeQuery = true)
У нас довольно странная и неудобная пагинация на мой взгляд, которая идеально ложится на LIMIT и OFFSET, неподдерживаемые hql. Была попытка превратить это в Pageble, но не самый удачный вариант. Например, при from = 3, size = 10.  Пришлось бы делать  PageRequest.of(0, 13) и подрезать первые 3 строки в выводе. Еще как вариант использовать setFirstResult(from)/setMaxResults(size), но мне не очень захотелось переписывать запрос через EntityManager. Поэтому оставил nativeQuery, кажется допустимым вариантом при курсорной пагинации

2023-08-22 21:15 UTC, pavlovartem97 commented
![image](https://github.com/pavlovartem97/java-shareit/assets/111424160/672a72f4-9e17-4090-871f-65ae755fa38a)
Понизил покрытие веток тестами до 0.5 из-за того, что проблемы с классом @Mapper. Там генерируется код с проверкой на null, но протестировать такое в реальных условиях нет нужды

2023-08-23 16:02 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/RequestRepository.java
> +            "OFFSET :offset ", nativeQuery = true)
Так это только ради пагинации? Тут `Pageable` вполне справится, например - 
```java
        Pageable pageable = PageRequest.of(from / size, size,
                Sort.by(Sort.Direction.DESC, BOOKING_START_DATE_FIELD_NAME));
```

2023-08-23 16:13 UTC, kalitva approved these changes

2023-08-23 16:13 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/RequestService.java
> +                Collectors.mapping(itemMapper::map, Collectors.toUnmodifiableList())));
Отличное решение использовать `groupingBy`

2023-09-03 12:16 UTC, merged